# Generated by Django 3.1.7 on 2021-04-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20210418_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='competition',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
