# Generated by Django 3.1.7 on 2021-04-18 01:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_emailsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competition', '0004_auto_20210418_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionportfolio',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CompetitionPortfolioHolding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competitionportfolio')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.stock')),
            ],
        ),
    ]
