# Generated by Django 3.1.7 on 2021-04-19 08:36

import competition.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_auto_20210419_1242'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='competition',
            name='endDate_gt_startDate',
        ),
        migrations.AddField(
            model_name='competition',
            name='submissionClose',
            field=models.DateTimeField(default=competition.models.get_default_close),
        ),
        migrations.AlterField(
            model_name='competition',
            name='endDate',
            field=models.DateTimeField(default=competition.models.get_default_end),
        ),
        migrations.AlterField(
            model_name='competition',
            name='startDate',
            field=models.DateTimeField(default=competition.models.get_default_start),
        ),
        migrations.AlterField(
            model_name='competitionportfolio',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competitionportfolio',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
