# Generated by Django 3.1.7 on 2021-04-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_auto_20210419_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='maxStartingValue',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=9),
        ),
    ]
