# Generated by Django 3.1.7 on 2021-04-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_competition_maxstartingvalue'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competitionportfolioholding',
            constraint=models.UniqueConstraint(fields=('portfolio', 'stock'), name='unique_holdings'),
        ),
    ]
