# Generated by Django 3.1.7 on 2021-04-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210321_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
