# Generated by Django 3.1.7 on 2021-03-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_stock_sector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="market",
        ),
    ]
