# Generated by Django 3.1.7 on 2021-03-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_remove_stock_market"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockdata",
            unique_together={("stock", "date")},
        ),
    ]
