# Generated by Django 3.1.7 on 2021-03-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_auto_20210330_0521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdata",
            name="close",
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="high",
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="low",
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="open",
            field=models.DecimalField(decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name="stockdata",
            name="volume",
            field=models.IntegerField(null=True),
        ),
    ]
