# Generated by Django 3.1.7 on 2021-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_auto_20210330_0554"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
