# Generated by Django 3.1.7 on 2021-04-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_emailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='predictedNextDayPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
