# Generated by Django 3.1.7 on 2021-04-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_stock_predictednextdayprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='isSandbox',
        ),
    ]
