# Generated by Django 3.1.7 on 2021-04-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210321_2014'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attitudetocomment',
            options={'verbose_name': 'attitude to comment', 'verbose_name_plural': 'attitudes to comment'},
        ),
        migrations.AlterModelOptions(
            name='attitudetopost',
            options={'verbose_name': 'attitude to post', 'verbose_name_plural': 'attitudes to post'},
        ),
        migrations.RenameField(
            model_name='attitudetocomment',
            old_name='to',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='attitudetopost',
            old_name='to',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
    ]
