# Generated by Django 3.1.7 on 2021-04-04 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_auto_20210404_1949'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attitudetocomment',
            unique_together={('comment', 'createdBy')},
        ),
        migrations.AlterUniqueTogether(
            name='attitudetopost',
            unique_together={('post', 'createdBy')},
        ),
    ]
