# Generated by Django 3.1.7 on 2021-04-06 16:38

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210406_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[portfolio.models.validate_non_negative], verbose_name='rating to the post posted portfolio (if applicable)'),
        ),
    ]
