# Generated by Django 3.1.7 on 2021-03-05 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colour",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                (
                    "hex",
                    models.CharField(
                        max_length=6,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
            ],
        ),
    ]
